// thanks man! Credit to https://gist.github.com/rviscomi/1479649
// notice that copyright from above link not included as directed
// since only the list of lorem ipsum words were used.
export const ipsum = [
  'lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur',
  'adipiscing', 'elit', 'curabitur', 'vel', 'hendrerit', 'libero',
  'eleifend', 'blandit', 'nunc', 'ornare', 'odio', 'ut',
  'orci', 'gravida', 'imperdiet', 'nullam', 'purus', 'lacinia',
  'a', 'pretium', 'quis', 'congue', 'praesent', 'sagittis', 
  'laoreet', 'auctor', 'mauris', 'non', 'velit', 'eros',
  'dictum', 'proin', 'accumsan', 'sapien', 'nec', 'massa',
  'volutpat', 'venenatis', 'sed', 'eu', 'molestie', 'lacus',
  'quisque', 'porttitor', 'ligula', 'dui', 'mollis', 'tempus',
  'at', 'magna', 'vestibulum', 'turpis', 'ac', 'diam',
  'tincidunt', 'id', 'condimentum', 'enim', 'sodales', 'in',
  'hac', 'habitasse', 'platea', 'dictumst', 'aenean', 'neque',
  'fusce', 'augue', 'leo', 'eget', 'semper', 'mattis', 
  'tortor', 'scelerisque', 'nulla', 'interdum', 'tellus', 'malesuada',
  'rhoncus', 'porta', 'sem', 'aliquet', 'et', 'nam',
  'suspendisse', 'potenti', 'vivamus', 'luctus', 'fringilla', 'erat',
  'donec', 'justo', 'vehicula', 'ultricies', 'varius', 'ante',
  'primis', 'faucibus', 'ultrices', 'posuere', 'cubilia', 'curae',
  'etiam', 'cursus', 'aliquam', 'quam', 'dapibus', 'nisl',
  'feugiat', 'egestas', 'class', 'aptent', 'taciti', 'sociosqu',
  'ad', 'litora', 'torquent', 'per', 'conubia', 'nostra',
  'inceptos', 'himenaeos', 'phasellus', 'nibh', 'pulvinar', 'vitae',
  'urna', 'iaculis', 'lobortis', 'nisi', 'viverra', 'arcu',
  'morbi', 'pellentesque', 'metus', 'commodo', 'ut', 'facilisis',
  'felis', 'tristique', 'ullamcorper', 'placerat', 'aenean', 'convallis',
  'sollicitudin', 'integer', 'rutrum', 'duis', 'est', 'etiam',
  'bibendum', 'donec', 'pharetra', 'vulputate', 'maecenas', 'mi',
  'fermentum', 'consequat', 'suscipit', 'aliquam', 'habitant', 'senectus',
  'netus', 'fames', 'quisque', 'euismod', 'curabitur', 'lectus',
  'elementum', 'tempor', 'risus', 'cras'
];

export const slang = [
  'adulting',
  'bae',
  'baller',
  'basic',
  'beat',
  'blessed',
  'bounce',
  'brah',
  'bruh',
  'bye felicia',
  'can\'t even',
  'canceled',
  'clap back',
  'crazy',
  'dank',
  'dope',
  'extra',
  'fam',
  'fine',
  'finna',
  'fomo',
  'gassed',
  'ghost',
  'goat',
  'gucci',
  'hangry',
  'heckin',
  'humble brag',
  'hundo-p',
  'hunty',
  'Ima',
  'jomo',
  'lay flame',
  'lit',
  'low key',
  'mood',
  'on fleek',
  'ratchet',
  'receipts',
  'salty',
  'savage',
  'sheeple',
  'ship',
  'shook',
  'slay',
  'snack',
  'snatched',
  'stan',
  'suh',
  'sus',
  'swerve',
  'swol',
  'tbh',
  'throwin shade',
  'trill',
  'trolls',
  'turnt',
  'wig snatched',
  'wizard',
  'woke',
  'yaas',
  'yeet',
  'yolo',
]

// export default [...lorem, ...slang]
export default slang